services:
  http-backend:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:password@pg-db:5432/postgres
    ports:
      - "4000:4000"
    depends_on:
      - pg-db

  pg-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
